# ============================================================================
# generate_regression_report.ps1
#
# 目的: 把已有的 ut-*.log + it-*.log + st-*.log + 各 *-summary-*.txt 汇总
#       成一份 markdown 报告, 不需要重跑测试。便于离线归因。
#
# 用法:
#   pwsh tests/scripts/generate_regression_report.ps1                     # 用最新
#   pwsh tests/scripts/generate_regression_report.ps1 -Stamp 20260920-180000
#
# 范围: Windows PowerShell 5.1+ / PowerShell 7+
# 作者: Mavis 接手 agent per DEC-008 (2026-09-20)
# ============================================================================

[CmdletBinding()]
param(
    [string]$Stamp,
    [string]$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot ".." "..")).Path,
    [string]$LogDir    = (Join-Path $PSScriptRoot ".." "logs"),
    [string]$ReportDir = (Join-Path $PSScriptRoot ".." "reports")
)

$ErrorActionPreference = 'Stop'

if (-not $Stamp) {
    $latest = Get-ChildItem -Path $LogDir -Filter "ut-summary-*.txt" -ErrorAction SilentlyContinue |
        Sort-Object LastWriteTime -Descending | Select-Object -First 1
    if (-not $latest) { throw "no ut-summary-* found in $LogDir. Run run_all_tests.ps1 first." }
    $Stamp = ($latest.BaseName -replace '^ut-summary-','')
}

New-Item -ItemType Directory -Force -Path $ReportDir | Out-Null

$utSummary = Get-ChildItem -Path $LogDir -Filter "ut-summary-$Stamp.txt" -ErrorAction SilentlyContinue | Select-Object -First 1
$itSummary = Get-ChildItem -Path $LogDir -Filter "it-summary-$Stamp.txt" -ErrorAction SilentlyContinue | Select-Object -First 1
$stSummary = Get-ChildItem -Path $LogDir -Filter "st-$Stamp.log"         -ErrorAction SilentlyContinue | Select-Object -First 1

$report = Join-Path $ReportDir "regression-$Stamp.md"

$md = @()
$md += "# IM1.0 回归测试报告 (offline 汇总)"
$md += ""
$md += "- **stamp**: $Stamp"
$md += "- **repo**: $RepoRoot"
$md += "- **logs**: $LogDir"
$md += ""
$md += "## 来源"
$md += ""
$md += "| 来源 | 路径 |"
$md += "|---|---|"
$md += "| UT summary | $($utSummary.FullName | ForEach-Object { $_.Replace($RepoRoot, '.') }) |"
$md += "| IT summary | $($itSummary.FullName | ForEach-Object { $_.Replace($RepoRoot, '.') }) |"
$md += "| ST log     | $($stSummary.FullName | ForEach-Object { $_.Replace($RepoRoot, '.') }) |"
$md += ""

function Append-Section($title, $path) {
    if (-not $path -or -not (Test-Path $path)) {
        $script:md += "### $title"
        $script:md += ""
        $script:md += "_missing_"
        $script:md += ""
        return
    }
    $script:md += "### $title"
    $script:md += ""
    $script:md += "Path: ``$($path.FullName -replace [regex]::Escape($RepoRoot), '.')``"
    $script:md += ""
    $script:md += '```'
    Get-Content $path | ForEach-Object { $script:md += $_ }
    $script:md += '```'
    $script:md += ""
}

Append-Section "UT"  $utSummary
Append-Section "IT"  $itSummary
Append-Section "ST"  $stSummary

$md += "---"
$md += "_Generated by `tests/scripts/generate_regression_report.ps1` at $(Get-Date -Format o)_"
$md | Out-File -FilePath $report -Encoding UTF8

Write-Host "[generate_regression_report] $report"